### ISSUE TITLE
Lower python version requirement

### ISSUE THREAD

**Issue by AmauryDeepki** [wlwg/aws-sns-message-validator#1]
Thanks for this package, it was exactly what I was looking for !

However, I can't use it per se on my project because I'm using python 3.6.3 and you require python>=3.7. I don't believe that you are using anything specific to python 3.7 (I copied your code and it was working properly : I got confirmed by aws and everything). So, would it be possible to lower the python requirement to at least 3.6.3 ?

Keep up the good work ! 💪

**Comment by wlwg** [comment]
I changed it to Python3.6. Let me know if you run into issues.

**Comment by khuongduybui** [comment]
I saw you changed it in README but you need to change it in setup.py too.

**Comment by wlwg** [comment]
> I saw you changed it in README but you need to change it in setup.py too.

Changed. Thank you.
