### ISSUE TITLE
make a release with a release number

### ISSUE THREAD

**Issue by jpcaruana** [wlwg/aws-sns-message-validator#2]
it would be great to make a stable release, even with a 0.1.0 version number, instead of installing this great lib with the master branch of your repo: it could break anytime

**Comment by rarylson** [comment]
I saw that this project is already on PyPI (https://pypi.org/project/sns-message-validator/). Nice!

I think it would be nice if the README was updated with this information: `pip install sns-message-validator`.

Congrats for your initiative.

**Comment by wlwg** [comment]
Thank you guys. @jpcaruana @rarylson 
I just made the first release.
