### ISSUE TITLE
Release latest version please?

### ISSUE THREAD

**Issue by khuongduybui** [wlwg/aws-sns-message-validator#7]
The last published version on PyPI still has the old, vulnerable cryptography 2x dependency.

Can you please adopt https://github.com/wlwg/aws-sns-message-validator/pull/6 and then release the next version?
Also please address https://github.com/wlwg/aws-sns-message-validator/issues/1#issuecomment-814125551 properly.

I made https://github.com/wlwg/aws-sns-message-validator/pull/8

**Comment by wlwg** [comment]
The issues mentioned in this issue have all been resolved.

**Comment by ab** [comment]
@wlwg Still not seeing v0.0.2 on PyPI. Are there plans to release it?
